# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE : pull_request
DEFAULT_BRANCH: main # Usually master or main
ENABLE:
  - JSON
DISABLE_LINTERS:
  - JSON_V8R 
  - JSON_JSONLINT
  - JSON_PRETTIER
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
PARALLEL: true
GITHUB_STATUS_REPORTER: true